dataset:
  dataset_name: prw-classification
  negatives_relative_path: negatives
  positives_relative_path: positives
  root_path: data/PRW
model:
  name: customnet
  task: classification
test:
  checkpoint_path: path/to/checkpoint
  num_workers: 4
  test_batch_size: 32
  test_num_repetitions: 33
training:
  accumulation_steps: 1
  early_stopping_patience: 0
  eval_batch_size: 32
  eval_num_repetitions: 1
  log:
    run_path: runs/default-run/
  lr: 5.0e-05
  metric_for_best_model: mu_auroc
  mode: max
  num_epochs: 10
  num_workers: 4
  train_batch_size: 32
